### ISSUE TITLE
mtdowling/cron-expression deprecated

### ISSUE THREAD

**Issue by asamaru7** [hmazter/laravel-schedule-list#15] opened 2018-02-26 01:55 UTC
laravel 5.6 : "Warning: Ambiguous class resolution" 

"mtdowling/cron-expression" is deprecated.
moved to https://github.com/dragonmantank/cron-expression.

**Comment by hmazter** [comment] 2018-02-27 20:38
Thanks, this is a duplicate of #12 and is fixed in the latest master, will tag a release very soon, hopefully.

**Closed as completed by hmazter** 2018-02-27 20:38 UTC
